export * from "./Benefits/components";
export * from "./Benefits";
export { default as Descubrí } from "./Descubrí/Descubrí";
export { default as Card } from "./Descubrí/components/Card";
export * from "./Header/components";
export * from "./Header";
export { default as Home } from "./Home";
export * from "./Offers/components/OfferCard";
export * from "./Offers/components";
export * from "./Offers";
export * from "./Relacionados/components/OfferCard";
export * from "./Relacionados/components";
export * from "./Relacionados";
export * from "./UltimaVista/components/OfferCard";
export * from "./UltimaVista/components";
export * from "./UltimaVista";
export { default as OffersDay } from "./OffersDay/OffersDay";
export { default as TextCard } from "./OffersDay/components/TextCard";
export { default as PopularCategories } from "./PopularCategories/PopularCategories";
export * from "./PopularCategories/components/CardCategories";
export * from "./Subscribe/components";
export * from "./Subscribe";
export { default as Tiendas } from "./Tiendas/Tiendas";
export * from "./Tiendas/components";
export * from "./index";
